server:
  bind: 0.0.0.0
  port: 8080


# MySQL配置
mysql:
  host: localhost:3306
  username: root
  password: M@k123456
  database: mall_go
  max-open-connections: 100 # 最大打开连接数 默认100
  max-idle-connections: 100 # 最大空闲连接数 默认100
  max-connection-life-time: 10 # 连接存活时间 默认10


# Redis 配置
redis:
  host: localhost
  port: 6379
  password: 123456
  database: 0


# JWT 配置
jwt:
  tokenHeader: "Authorization"
  tokenHead: "Bearer "
  realm: JWT  # JWT标识
  key: xpemkvLBGqotqHKRGI  # 服务端密钥
  timeout: 24 # token过期时间，单位：小时
  max-refresh: 24 # token刷新时间，单位：小时



